// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqxARZv6y83d-YDcVYZyRB0fUNPhbq0k',
    appId: '1:931595881121:ios:6d4914185d5b48475a7ee0',
    messagingSenderId: '931595881121',
    projectId: 'socialapp-4745a',
    storageBucket: 'socialapp-4745a.firebasestorage.app',
    iosBundleId: 'com.ravidkrisi.socialApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy80IJdbpEKeVxS9HNkzfg8MTf6AJyoYs',
    appId: '1:931595881121:android:0065901115f286095a7ee0',
    messagingSenderId: '931595881121',
    projectId: 'socialapp-4745a',
    storageBucket: 'socialapp-4745a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_4ccgwImH6I6zg0NrRapK5ln_mXZp9g',
    appId: '1:931595881121:web:13e5176363a96acd5a7ee0',
    messagingSenderId: '931595881121',
    projectId: 'socialapp-4745a',
    authDomain: 'socialapp-4745a.firebaseapp.com',
    storageBucket: 'socialapp-4745a.firebasestorage.app',
    measurementId: 'G-L4V5VYB8ND',
  );

}